version: "3.8"

services:
  backend:
    container_name: backend
    working_dir: /app
    build:
      context: ./packages/backend
      dockerfile: backend.dockerfile
    ports:
      - "3000:3000"

  frontend:
    container_name: frontend
    working_dir: /app
    build:
      context: ./packages/frontend
      dockerfile: frontend.dockerfile
    ports:
      - "8080:3000"

  database:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
