version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: ./packages/backend
      dockerfile: backend.dockerfile
    ports:
      - "8000:3000"
    volumes:
      - ./packages/backend:/app
    restart: unless-stopped

  frontend:
    container_name: frontend
    build:
      context: ./packages/frontend
      dockerfile: frontend.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./packages/frontend:/app
    restart: unless-stopped

  backend-database:
    container_name: backend-database
    image: postgres:latest
    environment:
      POSTGRES_USER: ${BACKEND_USER}
      POSTGRES_PASSWORD: ${BACKEND_PASSWORD}
      POSTGRES_DB: ${BACKEND_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  keycloak-database:
    container_name: keycloak-database
    image: postgres:latest
    environment:
      POSTGRES_USER: ${KC_DB_USER}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
      POSTGRES_DB: ${KC_DB}
    ports:
      - "3306:5432"
    volumes:
      - keycloak-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: ["start-dev", "--import-realm"]
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: ${KC_DB_USER}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB_URL: "jdbc:postgresql://keycloak-database:5432/${KC_DB}"
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
    ports:
      - 8080:8080
    depends_on:
      - keycloak-database
    volumes:
      - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json:ro

volumes:
  postgres-data:
  keycloak-data:
